In [1]:
from text2brick.models import GraphLegoWorldData
import numpy as np
from text2brick.dataset.dataset import MNISTDataset
from text2brick.gym import LegoEnv

In [2]:
table = np.array([[0, 0, 0, 0],
                  [1, 1, 0, 0],
                  [0, 1, 1, 0],
                  [1, 1, 0, 0]])

In [3]:
dataset = MNISTDataset()
array, _, _, _ = dataset.sample(sample_index=1)

In [4]:
env = LegoEnv(array.shape[0])
print(env)

LegoEnv(Environment Size: 28x28, 
Observation Space: MultiBinary((28, 28)), 
Action Space: MultiDiscrete([27 27]), 
Reward Function: Reward function : 1.0*IoU + 1.0*validity)


In [5]:
obs, reward, done, info = env.step((0, 14), array) # Valid
obs, reward, done, info = env.step((0, 14), array) # Overlap
obs, reward, done, info = env.step((0, 27), array) # Half of the brick is out of the world 
obs, reward, done, info = env.step((3, 14), array) # Invalid
obs, reward, done, info = env.step((1, 14), array) # Valid
print(obs)

Overlap: A brick already exists at (14, 0)
Outside: Brick at (27, 0) is out of the world
Invalid: Brick at (14, 3)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [6]:
graph = GraphLegoWorldData(img=table)
graph.add_brick(3, 0)
graph.add_brick(2, 0)
graph.print_graph()

Outside: Brick at (3, 0) is out of the world
Number of nodes: 4
Number of edges: 3
Node 0: {'x': 0, 'y': 0, 'validity': True}
Node 1: {'x': 1, 'y': 1, 'validity': True}
Node 2: {'x': 0, 'y': 2, 'validity': True}
Node 3: {'x': 2, 'y': 0, 'validity': True}
Edge (0, 1): {}
Edge (1, 2): {}
Edge (1, 3): {}


In [7]:
graph.graph_to_table()

array([[0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 1, 1, 1]])

In [8]:
sorted_nodes = sorted(graph.graph.nodes(data=True), key=lambda item: item[1]['y'])
sorted_nodes

[(0, {'x': 0, 'y': 0, 'validity': True}),
 (3, {'x': 2, 'y': 0, 'validity': True}),
 (1, {'x': 1, 'y': 1, 'validity': True}),
 (2, {'x': 0, 'y': 2, 'validity': True})]