In [1]:
from text2brick.models import GraphLegoWorldData
import numpy as np
#import torch
#from text2brick.dataset.dataset import MNISTDataset
#from text2brick.gym import LegoEnv


In [8]:
table = np.array([[0, 1, 1, 0],
                  [1, 1, 1, 1],
                  [1, 1, 1, 0],
                  [1, 1, 1, 1],
                  [0, 1, 1, 0],
                  [1, 1, 1, 1],])

In [12]:
lego_world = GraphLegoWorldData(table)
lego_world.get_brick_at_edge()

{'x': 2, 'y': 4, 'validity': True}

In [13]:
print(lego_world.graph_to_table())
for i in range(lego_world.nodes_num()):
    brick_removal = lego_world.get_brick_at_edge()
    lego_world.remove_brick(brick_removal.get('x'), brick_removal.get('y'))
    print(lego_world.graph_to_table())

[[0 1 1 0]
 [1 1 1 1]
 [1 1 0 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[[0 1 1 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[[0 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [1 1 0 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 1 0]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
print(lego_world.print_graph())

Number of nodes: 2
Number of edges: 0
Node 0: {'x': 0, 'y': 0, 'validity': True}
Node 1: {'x': 2, 'y': 0, 'validity': True}
None


In [3]:
# dataset = MNISTDataset()
# array, _, _, _ = dataset.sample(sample_index=1)

In [4]:
# env = LegoEnv(array.shape[0])
# print(env)

In [5]:
# obs, reward, done, info = env.step((0, 14), array) # Valid
# obs, reward, done, info = env.step((0, 14), array) # Overlap
# obs, reward, done, info = env.step((0, 27), array) # Half of the brick is out of the world 
# obs, reward, done, info = env.step((3, 14), array) # Invalid
# obs, reward, done, info = env.step((1, 14), array) # Valid
# print(obs)

In [6]:
graph = GraphLegoWorldData(img=table)
graph.add_brick(3, 0)
graph.add_brick(2, 0)
graph.print_graph()
graph.save_as_ldraw()

Outside: Brick at (3, 0) is out of the world
Number of nodes: 4
Number of edges: 3
Node 0: {'x': 0, 'y': 0, 'validity': True}
Node 1: {'x': 1, 'y': 1, 'validity': True}
Node 2: {'x': 0, 'y': 2, 'validity': True}
Node 3: {'x': 2, 'y': 0, 'validity': True}
Edge (0, 1): {}
Edge (1, 2): {}
Edge (1, 3): {}


In [13]:
data = graph.get_nodes()

for node, data in data: 
    print(node, data)

0 {'x': 0, 'y': 0, 'validity': True}
1 {'x': 1, 'y': 1, 'validity': True}
2 {'x': 0, 'y': 2, 'validity': True}
3 {'x': 2, 'y': 0, 'validity': True}


In [8]:
sub = graph.subgraph(3)
for node, data in sub.nodes(data=True):
    print(f"Node {node}: {data}")
for u, v,  in sub.edges():
    print(f"Edge ({u}, {v}):")

sub

Node 0: {'x': 0, 'y': 0, 'validity': True}
Node 1: {'x': 1, 'y': 1, 'validity': True}
Node 2: {'x': 0, 'y': 2, 'validity': True}
Edge (0, 1):
Edge (1, 2):


In [9]:
graph.graph_to_table()

array([[0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 1, 1, 1]])

In [10]:
data = graph.graph_to_torch()
c = torch.stack([data.x, data.y])
data.edge_index

tensor([[0, 1, 1],
        [1, 2, 3]])

In [11]:
from torch.utils.data import DataLoader
from text2brick.dataset import CustomDatasetGraph

dataset = CustomDatasetGraph()


In [12]:
train_data = DataLoader(dataset, batch_size=1, shuffle=True)

for i in range(2):
    x, edge_index, next_node = next(iter(train_data))
    print(f"Sample {i + 1}:")
    print(f"Node Features (x): {x}")
    print(f"Edge Index: {edge_index}")
    print(f"Next Node: {next_node}")
    print("-" * 30)

Sample 1:
Node Features (x): tensor([[[ 5,  7,  5,  7,  5,  7,  9,  6,  8, 10,  6,  8, 10,  8, 10, 12,  9,
          11, 10, 12, 14, 10, 12, 14, 11, 13, 15, 12, 14, 16, 14, 16, 14, 16,
          15, 17, 19, 15, 17, 19, 16, 18, 20, 16, 18, 20, 16, 18, 20, 19],
         [ 0,  0,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,
           6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 12, 12,
          13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 18]]])
Edge Index: tensor([[[ 0,  1,  2,  3,  4,  5,  5,  6,  6,  7,  8,  9, 11, 12, 13, 14, 14,
          15, 16, 17, 17, 18, 19, 20, 21, 22, 22, 23, 23, 24, 25, 25, 26, 26,
          28, 29, 30, 31, 32, 33, 33, 34, 35, 36, 37, 38, 38, 39, 39, 40, 41,
          42, 43, 44, 45, 47, 48],
         [ 2,  3,  4,  5,  7,  7,  8,  8,  9, 10, 11, 12, 13, 14, 16, 16, 17,
          17, 18, 18, 19, 21, 22, 23, 24, 24, 25, 25, 26, 27, 27, 28, 28, 29,
          30, 31, 32, 33, 34, 34, 35, 37, 38, 39, 40, 40, 41, 41, 42, 

In [1]:
from text2brick.gym import Text2Brick_v1
import torch
import numpy as np
from PIL import Image
from torchsummary import summary
from text2brick.gym import Text2Brick_v1, BrickPlacementGNN, CNN, SNN, PositionHead2D, MLP

image_target = np.random.rand(3, 224, 224)
image_environment = np.random.rand(3, 224, 224)

def numpy_to_pil(image_np):
    image_np = (image_np * 255).astype(np.uint8)
    image_np = image_np.transpose(1, 2, 0)
    return Image.fromarray(image_np)

image_target_pil = numpy_to_pil(image_target)
image_environment_pil = numpy_to_pil(image_environment)

# image_target_pil.show()
# image_environment_pil.show()

In [2]:
node_features = torch.randn(10, 2)  # 10 nodes with 2 features each
edge_index = torch.tensor([[0, 1, 2], [1, 2, 3]])  # Example edge connections

# Initialize the model
#model = Text2Brick_v1(image_target=image_target_pil)

In [3]:
gnn = BrickPlacementGNN()
gnn_result = gnn.forward(node_features, edge_index)
gnn_result.shape

torch.Size([1, 64])

In [4]:
snn = SNN(image_target=image_target_pil)
snn_result = snn.forward(image_environment_pil)
snn_result.shape

Using cache found in C:\Users\gourd/.cache\torch\hub\pytorch_vision_v0.10.0


torch.Size([1, 13, 13])

In [5]:
mlp = MLP((1, 13, 13), (1, 64))

In [6]:
reward_score = 1.0
reward = torch.tensor([reward_score], dtype=torch.float32).unsqueeze(1)
mlp_output = mlp.forward(snn_result, gnn_result, reward)

torch.Size([1, 169]) torch.Size([1, 64]) tensor([[1.]])


In [7]:
mlp_output.shape 

torch.Size([1, 16])

In [8]:
head = PositionHead2D(mlp_output_dim=(1, 16))

In [9]:
head.forward(mlp_output)

tensor([[0, 2]])

In [10]:
full_model = Text2Brick_v1(image_target=image_target_pil)

Using cache found in C:\Users\gourd/.cache\torch\hub\pytorch_vision_v0.10.0


In [11]:
full_model.forward(image_environment_pil, node_features, edge_index, reward)

torch.Size([1, 169]) torch.Size([1, 64]) tensor([[1.]])


tensor([[2, 5]])

In [5]:
from text2brick.dataset import CustomDatasetGraph

dataset = CustomDatasetGraph()

In [14]:
dataset.__getitem__(0)

(tensor([[ 9, 11,  9, 11, 10, 12, 11, 13, 11, 13],
         [ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4]]),
 tensor([[0, 1, 2, 3, 3, 4, 5, 5, 6, 7],
         [2, 3, 4, 4, 5, 6, 6, 7, 8, 9]]),
 tensor([12,  5], dtype=torch.int32))

In [15]:
dataset.__len__()

1

In [4]:
from text2brick.dataset import MNISTDataset
from text2brick.models import GraphLegoWorldData
from text2brick.utils.ImageUtils import array_to_image
mnist = MNISTDataset()

In [5]:
idx = 0
array, _, _, _ = mnist.sample(sample_index=idx)
lego_world = GraphLegoWorldData(array)

In [6]:
lego_world.graph.nodes(data=True)

NodeDataView({0: {'x': 18, 'y': 0, 'validity': True}, 1: {'x': 18, 'y': 1, 'validity': True}, 2: {'x': 17, 'y': 2, 'validity': True}, 3: {'x': 19, 'y': 2, 'validity': True}, 4: {'x': 16, 'y': 3, 'validity': True}, 5: {'x': 18, 'y': 3, 'validity': True}, 6: {'x': 14, 'y': 4, 'validity': True}, 7: {'x': 16, 'y': 4, 'validity': True}, 8: {'x': 18, 'y': 4, 'validity': True}, 9: {'x': 12, 'y': 5, 'validity': True}, 10: {'x': 14, 'y': 5, 'validity': True}, 11: {'x': 16, 'y': 5, 'validity': True}, 12: {'x': 11, 'y': 6, 'validity': True}, 13: {'x': 13, 'y': 6, 'validity': True}, 14: {'x': 15, 'y': 6, 'validity': True}, 15: {'x': 11, 'y': 7, 'validity': True}, 16: {'x': 13, 'y': 7, 'validity': True}, 17: {'x': 11, 'y': 8, 'validity': True}, 18: {'x': 13, 'y': 8, 'validity': True}, 20: {'x': 13, 'y': 9, 'validity': True}})

In [7]:
lego_world.graph_to_torch(deepcopy=True)

Data(edge_index=[2, 40], validity=[20], x=[20, 2])

In [3]:
lego_world.get_brick_at_edge()

TypeError: 'int' object is not subscriptable

In [ ]:
#load the first image from the mnist dataset
idx = 0
array, _, _, _ = mnist.sample(sample_index=idx) #already implemented
#load the graph from the image
lego_world = GraphLegoWorldData(array) #already implemented
#retrieve the brick at the edge or y the highest
# brick = lego_world.get_brick_at_edge() #to implement
# #remove brick from the graph
# updated_graph = lego_world.remove_brick(brick) #already implemented
# #convert the graph to an image
# current_build_img = updated_graph.graph_to_table() #already implemented

AttributeError: 'GraphLegoWorldData' object has no attribute 'get_brick_at_edge'

In [ ]:
array_to_image(array)

In [38]:
array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 

In [39]:
converted_graph = lego_world_ref.graph_to_table()

In [40]:
array_to_image(converted_graph)

In [23]:
vars(lego_world_ref.graph)

{'graph': {},
 '_node': {0: {'x': 9, 'y': 0, 'validity': True},
  1: {'x': 11, 'y': 0, 'validity': True},
  2: {'x': 13, 'y': 0, 'validity': True},
  3: {'x': 9, 'y': 1, 'validity': True},
  4: {'x': 11, 'y': 1, 'validity': True},
  5: {'x': 13, 'y': 1, 'validity': True},
  6: {'x': 9, 'y': 2, 'validity': True},
  7: {'x': 11, 'y': 2, 'validity': True},
  8: {'x': 13, 'y': 2, 'validity': True},
  9: {'x': 10, 'y': 3, 'validity': True},
  10: {'x': 12, 'y': 3, 'validity': True},
  11: {'x': 10, 'y': 4, 'validity': True},
  12: {'x': 12, 'y': 4, 'validity': True},
  13: {'x': 14, 'y': 4, 'validity': True},
  14: {'x': 11, 'y': 5, 'validity': True},
  15: {'x': 13, 'y': 5, 'validity': True},
  16: {'x': 7, 'y': 6, 'validity': True},
  17: {'x': 9, 'y': 6, 'validity': True},
  18: {'x': 11, 'y': 6, 'validity': True},
  19: {'x': 13, 'y': 6, 'validity': True},
  20: {'x': 15, 'y': 6, 'validity': True},
  21: {'x': 17, 'y': 6, 'validity': True},
  22: {'x': 19, 'y': 6, 'validity': True},
  2

In [1]:
from text2brick.dataset import LegoDatasetGenerator
from text2brick.gym import IoUValidityRewardFunc
reward_function = IoUValidityRewardFunc()
generator = LegoDatasetGenerator(reward_function=reward_function)

In [2]:
generator.generate_dataset(10)

100%|██████████| 10/10 [00:03<00:00,  2.57it/s]


In [1]:
from text2brick.dataset import LegoPretrainDataset
from torch_geometric.loader import DataLoader 
dataset = LegoPretrainDataset("./lego_dataset")
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

c:\Users\ebern\Documents\GitHub\Text2Bricks\text2brick\dataset\LegoDataset.py:25: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(file_path)


In [4]:
dataset.__getitem__(0)

(tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          ...,
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],
 
         [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          ...,
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],
 
         [[-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044,

In [3]:
from text2brick.gym import Text2Brick_v1

model = Text2Brick_v1()

for batch in dataloader:
    
    image_target = batch[0]
    current_build_img = batch[1]
    next_node = batch[2]
    reward = batch[3]
    current_graph = batch[4]
    output = model(current_build_img, current_graph, reward, image_target=image_target)
    print("Forward pass successful! Output shape:", output.shape)
    break


Using cache found in C:\Users\ebern/.cache\torch\hub\pytorch_vision_v0.10.0


x shape before gcn1: torch.Size([45, 2])
edge_index shape before gcn1: torch.Size([2, 102])
Forward pass successful! Output shape: torch.Size([2, 2])


In [3]:
output

tensor([[2, 0],
        [2, 0]])

In [ ]:
#TODO dimension problem to fix with the dataloader

from torch_geometric.loader import DataLoader 

# Define the DataLoader
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

# # Iterate through the DataLoader
for i, batch in enumerate(dataloader):
    target_images = batch[0]  # Tensors for target images
    current_images = batch[1]  # Tensors for current builds
    bricks_to_add = batch[2]  # Dictionaries with brick coordinates
    rewards = batch[3]  # Reward values
    current_graphs = batch[4]  # Batched graph data (PyG Data)
    print("-----------------------------------------------------------")
    print(f"Target image size: {batch[0].size()}")
    print(f"Current image size: {batch[1].size()}")
    print(f"Brick to add size: {batch[2].size()}")
    print(f"Reward size: {batch[3].size()}")
    print(f"Current graph: {batch[4]}")
    print(f"{batch[4].x}")
    print(f"Number of graphs in batch: {len(current_graphs)}")
    print(f"First graph nodes: {current_graphs[0].num_nodes}")

    if i == 200:
        break

-----------------------------------------------------------
Target image size: torch.Size([10, 3, 224, 224])
Current image size: torch.Size([10, 3, 224, 224])
Brick to add size: torch.Size([10, 2])
Reward size: torch.Size([10])
Current graph: DataBatch(x=[225], edge_index=[2, 490], y=[225], validity=[225], batch=[225], ptr=[11])
tensor([ 8, 10,  8, 10,  8, 10,  8, 10,  9, 11, 10, 12, 10, 12, 10, 12, 11, 13,
        11, 13, 12, 14, 13, 15, 13, 15, 14, 15, 17, 14, 16, 14, 14, 13, 15, 13,
        15, 13, 15, 14, 13, 15, 13, 15,  8, 10,  8, 10,  8, 10,  8, 10,  9, 11,
        10, 12, 10, 12, 10, 12, 11, 13, 11, 13, 12, 14, 13, 15, 13, 15, 14, 16,
        15, 17, 15, 17, 16, 18, 17, 19, 17, 19, 18, 13, 13, 13, 13, 14, 14, 14,
        14, 16, 15, 15, 10, 12, 14, 16,  9, 11, 13, 15, 17,  9, 11, 16, 18,  9,
        16, 18,  8, 16, 16,  7,  9, 11,  6,  8, 10,  6, 16, 15, 17, 16, 18, 17,
        19, 18, 14, 14, 14, 14, 14, 14,  5,  7,  9,  5,  7,  9, 11,  5,  7,  9,
        11, 13,  5,  7,  9, 1

In [7]:
current_graphs

DataBatch(x=[69], edge_index=[2, 148], y=[69], validity=[69], batch=[69], ptr=[5])

In [3]:
from torch_geometric.data import Data
import torch

def check_node_features(dataset):
    for i, data in enumerate(dataset):
        # Check if 'x' and 'y' attributes exist in the data object
        data = data[4]
        if not hasattr(data, 'x') or not hasattr(data, 'y'):
            print(f"Data index {i}: Missing 'x' or 'y' features!")
            continue  # Skip to the next dataset item
        
        # Check if the 'x' and 'y' features are non-empty
        if data.x is None or data.y is None:
            print(f"Data index {i}: 'x' or 'y' features are None!")
            return i, data
            
        # Check if 'x' and 'y' are valid tensors
        if not isinstance(data.x, torch.Tensor) or not isinstance(data.y, torch.Tensor):
            print(f"Data index {i}: 'x' or 'y' features are not tensors!")
            continue
        
        # Check if the 'x' tensor has the correct shape
        if data.x.size(0) == 0:
            print(f"Data index {i}: 'x' has no nodes!")
            continue
        
        # Check if 'y' is correctly shaped or has the expected dimensions
        if data.y.size(0) != data.x.size(0):
            print(f"Data index {i}: 'y' and 'x' have mismatched dimensions!")
            continue

        print(f"Data index {i}: 'x' and 'y' are present and valid.")

# Example usage with your dataset
check_node_features(dataset)

Data index 0: 'x' and 'y' are present and valid.
Data index 1: 'x' and 'y' are present and valid.
Data index 2: 'x' and 'y' are present and valid.
Data index 3: 'x' and 'y' are present and valid.
Data index 4: 'x' and 'y' are present and valid.
Data index 5: 'x' and 'y' are present and valid.
Data index 6: 'x' and 'y' are present and valid.
Data index 7: 'x' and 'y' are present and valid.
Data index 8: 'x' and 'y' are present and valid.
Data index 9: 'x' and 'y' are present and valid.
Data index 10: 'x' and 'y' are present and valid.
Data index 11: 'x' and 'y' are present and valid.
Data index 12: 'x' and 'y' are present and valid.
Data index 13: 'x' and 'y' are present and valid.
Data index 14: 'x' and 'y' are present and valid.
Data index 15: 'x' and 'y' are present and valid.
Data index 16: 'x' and 'y' are present and valid.
Data index 17: 'x' and 'y' are present and valid.
Data index 18: 'x' and 'y' are present and valid.
Data index 19: 'x' and 'y' are present and valid.
Data index

In [ ]:
dataset.__getitem__(84)[4]

Data(x=[1], edge_index=[2, 0], y=[1], validity=[1])

In [20]:
from torch_geometric.utils.convert import from_networkx, to_networkx

graph = to_networkx(dataset.__getitem__(84)[4])

In [24]:
dataset.__getitem__(84)[4].edge_index

tensor([], size=(2, 0), dtype=torch.int64)

In [20]:
from torch_geometric.data import DataLoader 
import traceback

# Create the DataLoader
dataloader = DataLoader(dataset, batch_size=1, shuffle=False)

# Wrap the DataLoader loop
for idx in range(len(dataset)):  # Iterate through the dataset indices
    try:
        print(f"Attempting to load sample {idx}...")
        sample = dataset[idx]  # Directly access the dataset to pinpoint the issue
        
        # Optional: Load the sample in the DataLoader if necessary
        # batch = next(iter(dataloader))
        
        print(f"Sample {idx} loaded successfully.")
    except Exception as e:
        print(f"Error while loading sample {idx}: {e}")
        print("Traceback:")
        traceback.print_exc()
        print("Problematic file:", dataset.files[idx])  # Assuming 'files' attribute lists dataset paths
        break  # Stop at the first problematic sample

Attempting to load sample 0...
Sample 0 loaded successfully.
Attempting to load sample 1...
Sample 1 loaded successfully.
Attempting to load sample 2...
Sample 2 loaded successfully.
Attempting to load sample 3...
Sample 3 loaded successfully.
Attempting to load sample 4...
Sample 4 loaded successfully.
Attempting to load sample 5...
Sample 5 loaded successfully.
Attempting to load sample 6...
Sample 6 loaded successfully.
Attempting to load sample 7...
Sample 7 loaded successfully.
Attempting to load sample 8...
Sample 8 loaded successfully.
Attempting to load sample 9...
Sample 9 loaded successfully.
Attempting to load sample 10...
Sample 10 loaded successfully.
Attempting to load sample 11...
Sample 11 loaded successfully.
Attempting to load sample 12...
Sample 12 loaded successfully.
Attempting to load sample 13...
Sample 13 loaded successfully.
Attempting to load sample 14...
Sample 14 loaded successfully.
Attempting to load sample 15...
Sample 15 loaded successfully.
Attempting t

c:\Users\ebern\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [10]:
dataloader.__len__()

357

In [12]:
dataloader.next()

AttributeError: 'DataLoader' object has no attribute 'next'