In [1]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!pip install python-dotenv --quiet
import dotenv
import os
dotenv.load_dotenv(
        os.path.join('/content/drive/MyDrive/vscode-ssh', '.env')
    )
password = os.getenv('PASSWORD')
github_access_token = os.getenv('GITHUB_ACCESS_TOKEN')

In [ ]:
!pip install colab_ssh --upgrade --quiet
from colab_ssh import launch_ssh_cloudflared, init_git_cloudflared

In [ ]:
launch_ssh_cloudflared(password)
init_git_cloudflared(repository_url=git_repo + ".git",
         personal_token=github_access_token, 
         branch="main",
         email="<email_for_github>",
         username="<github_username>")

In [ ]:
from text2brick.dataset import LegoDatasetGenerator
from text2brick.gym import IoUValidityRewardFunc
reward_function = IoUValidityRewardFunc()
generator = LegoDatasetGenerator(reward_function=reward_function)

In [2]:
generator.generate_dataset(10)

100%|██████████| 10/10 [00:05<00:00,  1.76it/s]


In [1]:
from text2brick.dataset import LegoPretrainDataset
from torch_geometric.loader import DataLoader 
dataset = LegoPretrainDataset("./lego_dataset")
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

c:\Users\ebern\Documents\GitHub\Text2Bricks\text2brick\dataset\LegoDataset.py:25: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(file_path)


In [2]:
from text2brick.gym import Text2Brick_v1
model = Text2Brick_v1()

Using cache found in C:\Users\ebern/.cache\torch\hub\pytorch_vision_v0.10.0


In [5]:
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

# Define the loss function (CrossEntropyLoss for classification tasks)
x_loss_fn = nn.CrossEntropyLoss()
y_loss_fn = nn.CrossEntropyLoss()

# Define optimizer
optimizer = optim.Adam(model.parameters(), lr=1e-3)

def train_model(model, dataloader, optimizer, x_loss_fn, y_loss_fn, num_epochs=10):
    model.train()  # Set the model to training mode

    for epoch in range(num_epochs):
        epoch_loss = 0.0
        
        # Loop over the batches of data
        for batch in tqdm(dataloader, desc=f"Epoch {epoch + 1}/{num_epochs}"):
            optimizer.zero_grad()  # Zero the parameter gradients

            image_target = batch[0]
            current_build_img = batch[1]
            next_node = batch[2]
            reward = batch[3]
            current_graph = batch[4]
            
            x_pred, y_pred = model(current_build_img, current_graph, reward, image_target=image_target, return_logits=True)
            x_true, y_true = next_node[:, 0], next_node[:, 1]

            # Compute loss for both x and y coordinates
            x_loss = x_loss_fn(x_pred, x_true)
            y_loss = y_loss_fn(y_pred, y_true)

            # Combine the losses (you can weight them differently if needed)
            loss = x_loss + y_loss
            
            # Backward pass and optimization
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        # Print epoch loss
        print(f"Epoch {epoch + 1}/{num_epochs}, Loss: {epoch_loss:.4f}")

# Run the training loop
train_model(model, dataloader, optimizer, x_loss_fn, y_loss_fn, num_epochs=10)


Epoch 1/10:   0%|          | 1/252 [00:00<01:03,  3.94it/s]

x shape before gcn1: torch.Size([39, 2])
edge_index shape before gcn1: torch.Size([2, 78])
torch.float32 torch.float32
tensor([15,  6]) tensor([10,  7])


Epoch 1/10:   1%|          | 2/252 [00:00<00:55,  4.50it/s]

x shape before gcn1: torch.Size([21, 2])
edge_index shape before gcn1: torch.Size([2, 38])
torch.float32 torch.float32
tensor([12,  5]) tensor([13,  1])


Epoch 1/10:   1%|          | 3/252 [00:00<00:57,  4.36it/s]

x shape before gcn1: torch.Size([101, 2])
edge_index shape before gcn1: torch.Size([2, 238])
torch.float32 torch.float32
tensor([19, 12]) tensor([12,  3])


Epoch 1/10:   2%|▏         | 4/252 [00:00<00:55,  4.45it/s]

x shape before gcn1: torch.Size([88, 2])
edge_index shape before gcn1: torch.Size([2, 196])
torch.float32 torch.float32
tensor([14, 15]) tensor([19, 15])


Epoch 1/10:   2%|▏         | 5/252 [00:01<00:54,  4.50it/s]

x shape before gcn1: torch.Size([44, 2])
edge_index shape before gcn1: torch.Size([2, 96])
torch.float32 torch.float32
tensor([13, 19]) tensor([ 7, 12])
x shape before gcn1: torch.Size([47, 2])
edge_index shape before gcn1: torch.Size([2, 108])
torch.float32 torch.float32
tensor([19, 14]) 

Epoch 1/10:   2%|▏         | 6/252 [00:01<00:53,  4.61it/s]

tensor([17,  7])


Epoch 1/10:   3%|▎         | 7/252 [00:01<00:56,  4.34it/s]

x shape before gcn1: torch.Size([24, 2])
edge_index shape before gcn1: torch.Size([2, 42])
torch.float32 torch.float32
tensor([14, 15]) tensor([4, 9])


Epoch 1/10:   3%|▎         | 8/252 [00:01<00:58,  4.16it/s]

x shape before gcn1: torch.Size([119, 2])
edge_index shape before gcn1: torch.Size([2, 278])
torch.float32 torch.float32
tensor([17, 11]) tensor([14,  1])


Epoch 1/10:   4%|▎         | 9/252 [00:02<01:01,  3.96it/s]

x shape before gcn1: torch.Size([94, 2])
edge_index shape before gcn1: torch.Size([2, 222])
torch.float32 torch.float32
tensor([12, 15]) tensor([8, 9])


Epoch 1/10:   4%|▍         | 10/252 [00:02<01:00,  3.97it/s]

x shape before gcn1: torch.Size([47, 2])
edge_index shape before gcn1: torch.Size([2, 100])
torch.float32 torch.float32
tensor([ 7, 17]) tensor([14,  8])


Epoch 1/10:   4%|▍         | 11/252 [00:02<00:57,  4.22it/s]

x shape before gcn1: torch.Size([61, 2])
edge_index shape before gcn1: torch.Size([2, 132])
torch.float32 torch.float32
tensor([12, 13]) tensor([14, 11])


Epoch 1/10:   5%|▌         | 13/252 [00:03<00:53,  4.49it/s]

x shape before gcn1: torch.Size([62, 2])
edge_index shape before gcn1: torch.Size([2, 138])
torch.float32 torch.float32
tensor([ 9, 20]) tensor([ 9, 10])
x shape before gcn1: torch.Size([88, 2])
edge_index shape before gcn1: torch.Size([2, 204])
torch.float32 torch.float32
tensor([ 8, 10]) tensor([8, 7])


Epoch 1/10:   6%|▌         | 15/252 [00:03<00:51,  4.64it/s]

x shape before gcn1: torch.Size([107, 2])
edge_index shape before gcn1: torch.Size([2, 250])
torch.float32 torch.float32
tensor([7, 8]) tensor([6, 3])
x shape before gcn1: torch.Size([17, 2])
edge_index shape before gcn1: torch.Size([2, 34])
torch.float32 torch.float32
tensor([11, 15]) tensor([ 0, 10])


Epoch 1/10:   6%|▋         | 16/252 [00:03<00:55,  4.22it/s]

x shape before gcn1: torch.Size([66, 2])
edge_index shape before gcn1: torch.Size([2, 144])
torch.float32 torch.float32
tensor([ 9, 19]) tensor([ 3, 15])


Epoch 1/10:   7%|▋         | 17/252 [00:03<00:54,  4.34it/s]

x shape before gcn1: torch.Size([57, 2])
edge_index shape before gcn1: torch.Size([2, 126])
torch.float32 torch.float32
tensor([13, 17]) tensor([ 9, 17])


Epoch 1/10:   7%|▋         | 18/252 [00:04<00:53,  4.41it/s]

x shape before gcn1: torch.Size([74, 2])
edge_index shape before gcn1: torch.Size([2, 174])
torch.float32 torch.float32
tensor([17, 16]) tensor([17,  7])


Epoch 1/10:   8%|▊         | 19/252 [00:04<00:52,  4.40it/s]

x shape before gcn1: torch.Size([41, 2])
edge_index shape before gcn1: torch.Size([2, 88])
torch.float32 torch.float32
tensor([13, 15]) tensor([10, 11])


Epoch 1/10:   8%|▊         | 20/252 [00:04<00:52,  4.40it/s]

x shape before gcn1: torch.Size([34, 2])
edge_index shape before gcn1: torch.Size([2, 62])
torch.float32 torch.float32
tensor([11,  7]) tensor([8, 4])


Epoch 1/10:   8%|▊         | 21/252 [00:04<00:52,  4.44it/s]

x shape before gcn1: torch.Size([71, 2])
edge_index shape before gcn1: torch.Size([2, 156])
torch.float32 torch.float32
tensor([18, 20]) tensor([16, 19])
x shape before gcn1: torch.Size([78, 2])
edge_index shape before gcn1: torch.Size([2, 170])


Epoch 1/10:   9%|▊         | 22/252 [00:05<00:50,  4.55it/s]

torch.float32 torch.float32
tensor([14, 16]) tensor([ 6, 14])


Epoch 1/10:   9%|▉         | 23/252 [00:05<00:49,  4.63it/s]

x shape before gcn1: torch.Size([24, 2])
edge_index shape before gcn1: torch.Size([2, 46])
torch.float32 torch.float32
tensor([17, 17]) tensor([9, 4])
x shape before gcn1: torch.Size([36, 2])
edge_index shape before gcn1: torch.Size([2, 72])
torch.float32 torch.float32
tensor([15,  7]) tensor([ 7, 10])


Epoch 1/10:  10%|▉         | 25/252 [00:05<00:51,  4.38it/s]

x shape before gcn1: torch.Size([104, 2])
edge_index shape before gcn1: torch.Size([2, 234])
torch.float32 torch.float32
tensor([ 9, 17]) tensor([ 6, 16])


Epoch 1/10:  11%|█         | 27/252 [00:06<00:48,  4.64it/s]

x shape before gcn1: torch.Size([57, 2])
edge_index shape before gcn1: torch.Size([2, 130])
torch.float32 torch.float32
tensor([18, 14]) tensor([18,  2])
x shape before gcn1: torch.Size([15, 2])
edge_index shape before gcn1: torch.Size([2, 28])
torch.float32 torch.float32
tensor([17, 12]) tensor([4, 5])


Epoch 1/10:  11%|█         | 28/252 [00:06<00:48,  4.66it/s]

x shape before gcn1: torch.Size([26, 2])
edge_index shape before gcn1: torch.Size([2, 48])
torch.float32 torch.float32
tensor([18, 13]) tensor([5, 8])


Epoch 1/10:  12%|█▏        | 29/252 [00:06<00:47,  4.71it/s]

x shape before gcn1: torch.Size([60, 2])
edge_index shape before gcn1: torch.Size([2, 130])
torch.float32 torch.float32
tensor([20, 13]) tensor([17,  6])
x shape before gcn1: torch.Size([14, 2])
edge_index shape before gcn1: torch.Size([2, 20])
torch.float32 torch.float32
tensor([14,  9]) tensor([3, 1])


Epoch 1/10:  13%|█▎        | 32/252 [00:07<00:44,  4.91it/s]

x shape before gcn1: torch.Size([77, 2])
edge_index shape before gcn1: torch.Size([2, 176])
torch.float32 torch.float32
tensor([19, 11]) tensor([17, 10])
x shape before gcn1: torch.Size([85, 2])
edge_index shape before gcn1: torch.Size([2, 198])
torch.float32 torch.float32
tensor([ 8, 19]) tensor([7, 6])


Epoch 1/10:  13%|█▎        | 33/252 [00:07<00:45,  4.87it/s]

x shape before gcn1: torch.Size([55, 2])
edge_index shape before gcn1: torch.Size([2, 124])
torch.float32 torch.float32
tensor([13, 11]) tensor([ 3, 15])
x shape before gcn1: torch.Size([37, 2])
edge_index shape before gcn1: torch.Size([2, 78])
torch.float32 torch.float32
tensor([ 6, 16]) tensor([ 8, 10])


Epoch 1/10:  14%|█▍        | 35/252 [00:07<00:44,  4.91it/s]

x shape before gcn1: torch.Size([33, 2])
edge_index shape before gcn1: torch.Size([2, 70])
torch.float32 torch.float32
tensor([6, 6]) tensor([3, 6])
x shape before gcn1: torch.Size([73, 2])
edge_index shape before gcn1: torch.Size([2, 164])
torch.float32 torch.float32
tensor([14, 17]) tensor([ 4, 15])


Epoch 1/10:  15%|█▍        | 37/252 [00:08<00:44,  4.84it/s]

x shape before gcn1: torch.Size([72, 2])
edge_index shape before gcn1: torch.Size([2, 160])
torch.float32 torch.float32
tensor([16, 14]) tensor([ 6, 16])
x shape before gcn1: torch.Size([9, 2])
edge_index shape before gcn1: torch.Size([2, 16])


Epoch 1/10:  15%|█▌        | 38/252 [00:08<00:44,  4.79it/s]

torch.float32 torch.float32
tensor([10, 11]) tensor([0, 4])


Epoch 1/10:  15%|█▌        | 39/252 [00:08<00:46,  4.55it/s]

x shape before gcn1: torch.Size([68, 2])
edge_index shape before gcn1: torch.Size([2, 150])
torch.float32 torch.float32
tensor([14,  9]) tensor([14, 10])


Epoch 1/10:  16%|█▌        | 40/252 [00:08<00:53,  3.99it/s]

x shape before gcn1: torch.Size([110, 2])
edge_index shape before gcn1: torch.Size([2, 258])
torch.float32 torch.float32
tensor([20,  9]) tensor([ 8, 10])


Epoch 1/10:  16%|█▋        | 41/252 [00:09<00:50,  4.16it/s]

x shape before gcn1: torch.Size([54, 2])
edge_index shape before gcn1: torch.Size([2, 116])
torch.float32 torch.float32
tensor([12, 20]) tensor([15,  7])


Epoch 1/10:  17%|█▋        | 42/252 [00:09<00:49,  4.23it/s]

x shape before gcn1: torch.Size([14, 2])
edge_index shape before gcn1: torch.Size([2, 22])
torch.float32 torch.float32
tensor([ 6, 15]) tensor([0, 6])


Epoch 1/10:  17%|█▋        | 43/252 [00:09<00:47,  4.38it/s]

x shape before gcn1: torch.Size([99, 2])
edge_index shape before gcn1: torch.Size([2, 232])
torch.float32 torch.float32
tensor([10, 17]) tensor([8, 9])


Epoch 1/10:  17%|█▋        | 44/252 [00:09<00:46,  4.50it/s]

x shape before gcn1: torch.Size([29, 2])
edge_index shape before gcn1: torch.Size([2, 52])
torch.float32 torch.float32
tensor([7, 9]) tensor([2, 2])
x shape before gcn1: torch.Size([108, 2])
edge_index shape before gcn1: torch.Size([2, 252])


Epoch 1/10:  18%|█▊        | 45/252 [00:10<00:45,  4.58it/s]

torch.float32 torch.float32
tensor([16, 23]) tensor([19,  3])


Epoch 1/10:  18%|█▊        | 46/252 [00:10<00:45,  4.48it/s]

x shape before gcn1: torch.Size([78, 2])
edge_index shape before gcn1: torch.Size([2, 170])
torch.float32 torch.float32
tensor([19, 13]) tensor([15, 17])


Epoch 1/10:  19%|█▊        | 47/252 [00:10<00:44,  4.58it/s]

x shape before gcn1: torch.Size([30, 2])
edge_index shape before gcn1: torch.Size([2, 60])
torch.float32 torch.float32
tensor([19, 12]) tensor([15,  6])


Epoch 1/10:  19%|█▉        | 48/252 [00:10<00:49,  4.11it/s]

x shape before gcn1: torch.Size([16, 2])
edge_index shape before gcn1: torch.Size([2, 28])
torch.float32 torch.float32
tensor([13, 17]) tensor([5, 7])


Epoch 1/10:  19%|█▉        | 49/252 [00:11<00:49,  4.12it/s]

x shape before gcn1: torch.Size([78, 2])
edge_index shape before gcn1: torch.Size([2, 172])
torch.float32 torch.float32
tensor([18, 10]) tensor([14,  5])


Epoch 1/10:  20%|██        | 51/252 [00:11<00:44,  4.48it/s]

x shape before gcn1: torch.Size([50, 2])
edge_index shape before gcn1: torch.Size([2, 110])
torch.float32 torch.float32
tensor([12, 11]) tensor([11,  8])
x shape before gcn1: torch.Size([15, 2])
edge_index shape before gcn1: torch.Size([2, 28])
torch.float32 torch.float32
tensor([10, 12]) tensor([1, 7])


Epoch 1/10:  21%|██        | 52/252 [00:11<00:43,  4.60it/s]

x shape before gcn1: torch.Size([38, 2])
edge_index shape before gcn1: torch.Size([2, 72])
torch.float32 torch.float32
tensor([14, 18]) tensor([13, 12])


Epoch 1/10:  21%|██        | 53/252 [00:11<00:43,  4.56it/s]

x shape before gcn1: torch.Size([107, 2])
edge_index shape before gcn1: torch.Size([2, 252])
torch.float32 torch.float32
tensor([ 8, 14]) tensor([15,  2])


Epoch 1/10:  21%|██▏       | 54/252 [00:12<00:43,  4.55it/s]

x shape before gcn1: torch.Size([36, 2])
edge_index shape before gcn1: torch.Size([2, 70])
torch.float32 torch.float32
tensor([13, 19]) tensor([ 7, 17])


Epoch 1/10:  22%|██▏       | 55/252 [00:12<00:42,  4.59it/s]

x shape before gcn1: torch.Size([45, 2])
edge_index shape before gcn1: torch.Size([2, 96])
torch.float32 torch.float32
tensor([20,  7]) tensor([14,  0])


Epoch 1/10:  22%|██▏       | 56/252 [00:12<00:42,  4.58it/s]

x shape before gcn1: torch.Size([24, 2])
edge_index shape before gcn1: torch.Size([2, 42])
torch.float32 torch.float32
tensor([12, 17]) tensor([14,  4])


Epoch 1/10:  23%|██▎       | 57/252 [00:12<00:48,  3.98it/s]

x shape before gcn1: torch.Size([50, 2])
edge_index shape before gcn1: torch.Size([2, 110])
torch.float32 torch.float32
tensor([ 6, 15]) tensor([6, 6])
x shape before gcn1: torch.Size([56, 2])
edge_index shape before gcn1: torch.Size([2, 126])
torch.float32 torch.float32


Epoch 1/10:  23%|██▎       | 58/252 [00:13<00:45,  4.27it/s]

tensor([16, 19]) tensor([16,  6])
x shape before gcn1: torch.Size([35, 2])
edge_index shape before gcn1: torch.Size([2, 78])


Epoch 1/10:  23%|██▎       | 59/252 [00:13<00:43,  4.42it/s]

torch.float32 torch.float32
tensor([15, 12]) tensor([15,  2])
x shape before gcn1: torch.Size([84, 2])
edge_index shape before gcn1: torch.Size([2, 196])
torch.float32 torch.float32
tensor([17, 11]) tensor([14, 16])


Epoch 1/10:  24%|██▍       | 61/252 [00:13<00:41,  4.65it/s]

x shape before gcn1: torch.Size([59, 2])
edge_index shape before gcn1: torch.Size([2, 130])
torch.float32 torch.float32
tensor([ 5, 17]) tensor([ 3, 18])


Epoch 1/10:  25%|██▍       | 62/252 [00:13<00:41,  4.62it/s]

x shape before gcn1: torch.Size([57, 2])
edge_index shape before gcn1: torch.Size([2, 128])
torch.float32 torch.float32
tensor([13, 18]) tensor([9, 8])
x shape before gcn1: torch.Size([22, 2])
edge_index shape before gcn1: torch.Size([2, 44])
torch.float32 torch.float32
tensor([18,  6]) tensor([5, 1])


Epoch 1/10:  25%|██▌       | 64/252 [00:14<00:39,  4.76it/s]

x shape before gcn1: torch.Size([113, 2])
edge_index shape before gcn1: torch.Size([2, 268])
torch.float32 torch.float32
tensor([16,  8]) tensor([15,  2])


Epoch 1/10:  26%|██▌       | 65/252 [00:14<00:38,  4.82it/s]

x shape before gcn1: torch.Size([108, 2])
edge_index shape before gcn1: torch.Size([2, 246])
torch.float32 torch.float32
tensor([12, 11]) tensor([16, 16])
x shape before gcn1: torch.Size([30, 2])
edge_index shape before gcn1: torch.Size([2, 64])


Epoch 1/10:  26%|██▌       | 66/252 [00:14<00:39,  4.75it/s]

torch.float32 torch.float32
tensor([15, 10]) tensor([14,  1])


Epoch 1/10:  27%|██▋       | 67/252 [00:14<00:40,  4.62it/s]

x shape before gcn1: torch.Size([96, 2])
edge_index shape before gcn1: torch.Size([2, 222])
torch.float32 torch.float32
tensor([7, 9]) tensor([ 9, 10])


Epoch 1/10:  27%|██▋       | 68/252 [00:15<00:46,  3.97it/s]

x shape before gcn1: torch.Size([82, 2])
edge_index shape before gcn1: torch.Size([2, 182])
torch.float32 torch.float32
tensor([18, 19]) tensor([ 6, 17])


Epoch 1/10:  27%|██▋       | 69/252 [00:15<00:46,  3.97it/s]

x shape before gcn1: torch.Size([93, 2])
edge_index shape before gcn1: torch.Size([2, 214])
torch.float32 torch.float32
tensor([ 9, 19]) tensor([14, 17])


Epoch 1/10:  28%|██▊       | 70/252 [00:15<00:47,  3.81it/s]

x shape before gcn1: torch.Size([102, 2])
edge_index shape before gcn1: torch.Size([2, 242])
torch.float32 torch.float32
tensor([20, 14]) tensor([13,  2])


Epoch 1/10:  28%|██▊       | 71/252 [00:16<00:48,  3.75it/s]

x shape before gcn1: torch.Size([47, 2])
edge_index shape before gcn1: torch.Size([2, 104])
torch.float32 torch.float32
tensor([20, 14]) tensor([10,  6])


Epoch 1/10:  29%|██▊       | 72/252 [00:16<00:47,  3.83it/s]

x shape before gcn1: torch.Size([83, 2])
edge_index shape before gcn1: torch.Size([2, 188])
torch.float32 torch.float32
tensor([ 7, 19]) tensor([11, 11])


Epoch 1/10:  29%|██▉       | 73/252 [00:16<00:46,  3.87it/s]

x shape before gcn1: torch.Size([70, 2])
edge_index shape before gcn1: torch.Size([2, 146])
torch.float32 torch.float32
tensor([16,  6]) tensor([14,  5])


Epoch 1/10:  29%|██▉       | 74/252 [00:16<00:45,  3.95it/s]

x shape before gcn1: torch.Size([55, 2])
edge_index shape before gcn1: torch.Size([2, 112])
torch.float32 torch.float32
tensor([21, 15]) tensor([ 5, 15])


Epoch 1/10:  30%|██▉       | 75/252 [00:17<00:48,  3.64it/s]

x shape before gcn1: torch.Size([60, 2])
edge_index shape before gcn1: torch.Size([2, 134])
torch.float32 torch.float32
tensor([13, 16]) tensor([18,  1])


Epoch 1/10:  30%|███       | 76/252 [00:17<00:40,  4.36it/s]

x shape before gcn1: torch.Size([61, 2])
edge_index shape before gcn1: torch.Size([2, 132])
torch.float32 torch.float32
tensor([13, 20]) tensor([ 6, 16])


KeyError: 'saved'